[package]
name = "dstnd-stun-api"
version = "0.1.0"
authors = ["Gabriel C. Troia <catalin.troia@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.4"
ws = "0.9.1"